### ISSUE TITLE
Something prevents Babele from translating CoM compendium

### ISSUE THREAD

**Issue by phenomen** [taragnor/city-of-mist#55]
I'm working on localization and this is the first system with compendium that cannot be translated with [Babele](https://gitlab.com/riccisi/foundryvtt-babele). I guess there is something in the initialization or caching that interferes with Babele - most likely `CityDB` loads data before it being translated.

Something like this should translate questions, but it doesn't - when I open a themebook in compendium it has original strings.

`city-of-mist.themebook.json`
```json
{
  "label": "Themebooks",
  "mapping": {
    "powers": "data.power_questions",
    "weakness": "data.weakness_questions"
  },
  "entries": {
    "Adaptation": {
      "name": "Translated Adaptation",
      "powers": {
        "A": {
          "question": "Hello World"
        }
      }
    }
  }
}
```

I would greatly appreciate if you could take a look.

**Comment by phenomen** [comment]
I've tinkered with DB stuff, and it seems it is indeed a culprit of the issue.
I've tried to add this in `module/tools/db-accessor.mjs`
```js
  static async init() {
    Hooks.once("ready", () => {
      if (typeof Babele !== "undefined") {
        Hooks.once("babele.ready", async () => {
          this._loadPacks();
        });
      } else {
        this._loadPacks();
      }
    });
    this._initHooks();
    console.log("Database initialized");
    Hooks.callAll("DB Ready");
  }
}
```

But now I have duplication issue where every Themebook is displayed twice when I click "Add Themebook" in the character sheet (one is translated and another is not).

**Comment by taragnor** [comment]
I probably don't know how Babele works well enough to really generate a fix for that. 

If it's creating virtual compendiums, then it's likely why you're seeing both versions. Since the translated and non-translated ones  both exist and get lumped together. I don't know if Babele offers a way to sort between what's converted and what isn't. 

I'll put in your partial solution there, which at least creates a translated copy. People can at least ignore the non-translated one. It isn't perfect, but at the moment I'm just not familiar enough with Babele and how it works to give a true fix.

**Comment by phenomen** [comment]
> I'll put in your partial solution there, which at least creates a translated copy. People can at least ignore the non-translated one. It isn't perfect, but at the moment I'm just not familiar enough with Babele and how it works to give a true fix.

It's better to not include it as-is. It's a very... unwanted result.
I will try to figure out how to not create a duplicate options in the themebook question select dialog and then create a pull request.
